schema: "classroom50/repo-config/v1"
classroom: "comp-395-2-deep-learning"
assignment: "lab-2-breast-cancer-detection"
owner:
  username: "Mia22bms"
  id: 243204693
  accepted_at: "2026-09-30T05:11:46Z"
source:
  owner: "AI-at-Oxy"
  owner_id: 253783941
  repo: "lab-2-breast-cancer"
  branch: "main"
